### PR TITLE
Add Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by a-ira**
Hi @bparmentier . I added a brazilian portuguese translation.

Feel free to merge ;)
## 

'Akira

### CODE REVIEW

**Comment by bparmentier** [comment]
Thanks!

**Comment by a-ira** [comment]
You're welcome. Thank you for the great app :)

**Comment by bparmentier** [comment]
I will update the app as soon as I have some spare time, sorry for the delay.

**Comment by a-ira** [comment]
No problems. I'm glad to contribute :)

**Pull request merged**
